version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=DocHelper;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 4080:80
      - 4443:443
    depends_on:
      - db
    restart: on-failure

  cabinet:
    image: ${DOCKER_REGISTRY-}cabinet-app
    build:
      context: .
      dockerfile: src/CabinetApp/Dockerfile
    ports:
      - 5080:80
      - 5443:443
    depends_on:
      - postgres
    restart: on-failure

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Your_password123"
      - "ACCEPT_EULA=Y"
        
  postgres:
    image: "postgres: latest"
    ports:
      - 5432:5432