import {Specialty} from './specialty';

export const SPECIALTY: Specialty[] = [
  { title: 'Акушер-гинеколог', alias: 'akusher-ginekolog', count: 20, active: true },
  { title: 'Аллерголог', alias: 'allergolog', count: 30, active: true },
  { title: 'Андролог', alias: 'androlog', count: 10, active: true },
  { title: 'Анестезиолог-реаниматолог', alias: 'anesteziolog', count: 20, active: true },
  { title: 'Аудиометрист', alias: 'audiometrist', count: 220, active: true },
  { title: 'Венеролог', alias: 'venerolog', count: 20, active: true },
  { title: 'Вертебролог', alias: 'vertebrolog', count: 52, active: true },
  { title: 'Гастроэнтеролог', alias: 'gastroenterolog', count: 2022, active: true },
  { title: 'Гематолог', alias: 'gematolog', count: 2210, active: true },
  { title: 'Генетик', alias: 'genetik', count: 20, active: true },
  { title: 'Гепатолог', alias: 'gepatolog', count: 1220, active: true },
  { title: 'Гомеопат', alias: 'gomeopat', count: 220, active: true },
  { title: 'Дерматовенеролог', alias: 'dermatovenerolog', count: 123, active: true },
  { title: 'Дерматолог', alias: 'dermatolog', count: 2320, active: true },
  { title: 'Дефектолог', alias: 'defektolog', count: 1, active: true },
  { title: 'Диетолог', alias: 'dietolog', count: 56, active: false },
  { title: 'Иммунолог', alias: 'immunolog', count: 2345, active: true },
  { title: 'Инфекционист', alias: 'infekcionist', count: 234, active: true },
  { title: 'Пластический хирург', alias: 'plasticheskij-hirur', count: 270, active: true },
  { title: 'Подолог', alias: 'podolog', count: 364, active: true },
  { title: 'Проктолог', alias: 'proktolog', count: 2356, active: false },
  { title: 'Ревматолог', alias: 'revmatolog', count: 238, active: true },
  { title: 'Рентгенолог', alias: 'rentgenolog', count: 10, active: false },
];
